### ISSUE TITLE
Erro "hierarchyMap = new Map()"

### ISSUE THREAD

**Issue by williankeller** [ciandt-dev/gulp-boilerplate#56]
Pessoal temos um erro de execução do gulp. Foi encontrada pelo nosso amigo @diegograssato.

Segue:

```shell
/gulp-boilerplate/node_modules/stylelint/dist/rules/indentation/index.js:26
var hierarchyMap = new Map();
                       ^
ReferenceError: Map is not defined
    at Object.<anonymous> (/home/wkeller/sites/gulp-boilerplate/node_modules/stylelint/dist/rules/indentation/index.js:26:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/wkeller/sites/gulp-boilerplate/node_modules/stylelint/dist/rules/index.js:181:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Eu clonei aqui e realmente o erro acontece.

**Comment by waltercassiano** [comment]
Eu testei aqui e aconteceu também de primeira.
Eu estou fazendo alguns testes assim que terminar eu envio, mas aparentemente é só atualizar a versão do node do travis ci

**Comment by arkhi** [comment]
@williankeller: Sorry, I’m not fluent in Portuguese, but for people ending on this bug, you can check http://austinpray.com/ops/2015/09/20/change-travis-node-version.html which is a working solution
