### ISSUE TITLE
Python required to install browser sync

### ISSUE THREAD

**Issue by caiquegtr** [ciandt-dev/gulp-boilerplate#58]
Está sendo necessário a prévia instalação do Python para que seja instalado o Browser Sync, caso não o tenha instalado na máquina ele dará este erro:

C:\Users\caique\AppData\Roaming\npm\node_modules\browser-sync\node_modules\bufferutil {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Users\caique\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\caique\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\caique\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\caique\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\caique\AppData\Roaming\npm\node_modules\browser-sync\node_modules\bufferutil
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\caique\AppData\Roaming\npm\node_modules\browser-sync\node_modules\utf-8-validate
> node-gyp rebuild

**Comment by dsoldera** [comment]
Isso ja aconteceu comigo. Me parece que fazer a instalaçao do Plugin do Python.

Dá uma olhada nesses links:

http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm

http://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

**Comment by waltercassiano** [comment]
@caiquegtr ... Passa pra gente  as versões do node e npm ... 

$ node -v
$ npm -v

**Comment by caiquegtr** [comment]
node v 5.4.1npm v 3.5.3

Date: Tue, 26 Jan 2016 08:36:40 -0800

**Comment by waltercassiano** [comment]
@caiquegtr .. tenta rodar o browser-sync, apesar destas msg ele deve estar funcionando.
